-- CreateTable
CREATE TABLE "User" (
    "chatId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "notify" BOOLEAN NOT NULL,
    "joined" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "active" BOOLEAN NOT NULL DEFAULT true
);
